class AsyncioError(Exception):
    """Exception raised for errors in the asyncio process."""

    pass
